schema_version = "1.0.0"

id = "Replicant2Blender"
version = "0.6.1"
name = "Replicant2Blender (NieR Replicant ver.1.2247... Mesh Pack Importer)"
tagline = "Import NieR Replicant Mesh Pack"
maintainer = "Woeful_Wolf"
type = "add-on"
tags = ["Import-Export"]
website = "https://github.com/WoefulWolf/Replicant2Blender"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

wheels = []

[permissions]
files = "Import NieR Replicant Mesh Pack from disk"