schema_version = "1.0.0"

id = "replicant2blender"
version = "0.12.1"
name = "Replicant2Blender (NieR Replicant ver.1.2247... Mesh Pack Importer)"
tagline = "Import NieR Replicant Mesh Pack"
maintainer = "Woeful_Wolf"
type = "add-on"
tags = ["Import-Export"]
website = "https://github.com/WoefulWolf/Replicant2Blender"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

wheels = [
  "./wheels/imageio-2.37.2-py3-none-any.whl",
  "./wheels/llvmlite-0.45.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/llvmlite-0.45.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
  "./wheels/llvmlite-0.45.1-cp311-cp311-win_amd64.whl",
  "./wheels/numba-0.62.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/numba-0.62.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
  "./wheels/numba-0.62.1-cp311-cp311-win_amd64.whl",
  "./wheels/pillow-12.0.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/pillow-12.0.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/pillow-12.0.0-cp311-cp311-win_amd64.whl",
  "./wheels/puredds-0.4.1-py3-none-any.whl",
]

[permissions]
files = "Import NieR Replicant Mesh Pack from disk"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
]